### ISSUE TITLE
possible solution for steam

### ISSUE THREAD

**Issue by Francesco149** [nonchip/steam_workaround_fsoverflow#1]
while trying to solve the same issue i noticed that the calls can return errno 75 and non-zero and even if you override the values steam bails out because of that.

clearing errno to 0 and returning 0 in the hooks might solve the problem. I have my own set of hooks doing this and they seem to work so far

**Comment by Francesco149** [comment]
... also it seems that the highest supported value for blocks * blocksize is ```(INT_MAX>>1)``` rather than INT_MAX, otherwise some games will still see no space

**Comment by Francesco149** [comment]
> ... also it seems that the highest supported value for blocks * blocksize is `(INT_MAX>>1)` rather than INT_MAX, otherwise some games will still see no space

nevermind, ```(INT_MAX<<9)``` also works and reports 1TB free

but yeah, clearing errno and returning 0 should fix it

**Comment by nonchip** [comment]
thanks for the input, sadly i can't test it anymore though because my specific issue is fixed by steam, but if you want to send a PR you tested i'll merge it, otherwise i can try to implement it later but can't test it then

**Comment by nonchip** [comment]
thing is though, steam was not only failing but actually in some places still showing the wrong values, as if it was clearing LD_PRELOAD while it spawned some of its helper processes maybe. so no idea if that'll actually help in the end even though it theoretically should
